import { link } from "fs";

export type Lang = "de" | "en";

export const nav = {
  de: [
    { path: "/", label: "Startseite" },
    { path: "/ueber-uns", label: "Über uns" },
    { path: "/projekte", label: "Projekte" },
    { path: "/aktuelles", label: "Aktuelles" },
    { path: "/mitmachen", label: "Mitmachen" },
    { path: "/partner", label: "Partner" },
    { path: "/kontakt", label: "Kontakt" },
  ],
  en: [
    { path: "/", label: "Home" },
    { path: "/ueber-uns", label: "About us" },
    { path: "/projekte", label: "Projects" },
    { path: "/aktuelles", label: "News & Events" },
    { path: "/mitmachen", label: "Get involved" },
    { path: "/partner", label: "Partners" },
    { path: "/kontakt", label: "Contact" },
  ],
};

export const org = {
  name: "Miteinander in Bergedorf e.V.",
  short: "MiB e.V.",
  street: "Weidenbaumsweg 54",
  city: "21035 Hamburg",
  postfach: "Postfach 808115 · 21015 Hamburg",
  district: "Neuallermöhe · Bergedorf",
  email: "info@mib-ev.de",
  phone: "+49 (0) 40 4608 2222",
  phoneRaw: "040 4608 2222",
  boardName: "Henry Akanno",
  boardPhone: "0174 1349 339",
  web: "www.mib-ev.de",
  register: "VR 22314, Amtsgericht Hamburg",
  ustId: "17/451/08764",
  bankName: "Hamburger Sparkasse",
  iban: "DE00 2005 0550 0000 0000 00",
  bic: "HASPDEHHXXX",
};

const de = {
  cta: {
    primary: "Projekte entdecken",
    secondary: "Mitmachen & unterstützen",
    donate: "Jetzt spenden",
    contact: "Kontakt aufnehmen",
    more: "Mehr erfahren",
    all: "Alle ansehen",
    membership: "Mitglied werden",
    volunteer: "Ehrenamtlich engagieren",
  },
  home: {
    kicker: "Integration · Bildung · Begegnung in Hamburg-Bergedorf",
    title: "Miteinander leben.\nGemeinsam gestalten.",
    lead:
      "Wir stärken die Integration von Familien, Kindern und Jugendlichen unterschiedlicher Herkunft – mit besonderem Fokus auf afrikanische Communities in Bergedorf und Neuallermöhe. Durch Begegnung, Bildung und gegenseitiges Lernen schaffen wir einen Stadtteil, in dem sich alle zugehörig fühlen.",
    statsTitle: "Seit 2014 im Stadtteil verwurzelt",
    stats: [
      { value: "2014", label: "von Anwohner:innen in Neuallermöhe gegründet" },
      { value: "8+", label: "laufende Projekte & Formate" },
      { value: "120+", label: "begleitete Kinder & Jugendliche" },
      { value: "20+", label: "aktive Ehrenamtliche" },
    ],
    missionKicker: "Unsere Mission",
    missionTitle: "Begegnung schafft Zugehörigkeit",
    missionText:
      "Integration gelingt dort, wo Menschen sich begegnen, einander zuhören und gemeinsam etwas aufbauen. Miteinander in Bergedorf e.V. ist ein Ort für Bildung, Kultur und Teilhabe – offen für alle Menschen im Stadtteil, unabhängig von Herkunft, Religion oder Sprache. Unser besonderes Augenmerk gilt den afrikanischen Communities in Bergedorf und Neuallermöhe.",
    pillars: [
      {
        icon: "book",
        title: "Bildung & Förderung",
        text: "Schülerhilfe, Mentoring und Beratung – damit junge Menschen ihre Chancen wirklich nutzen können.",
      },
      {
        icon: "globe",
        title: "Interkultureller Dialog",
        text: "Filmabende, Feste und Gespräche, die Vorurteile abbauen und Nachbarschaft zusammenbringen.",
      },
      {
        icon: "hands",
        title: "Teilhabe & Empowerment",
        text: "Wir begleiten Familien im Alltag, bei Behörden und auf dem Weg in Ausbildung und Beruf.",
      },
    ],
    projectsKicker: "Unsere Arbeit",
    projectsTitle: "Unsere wichtigsten Projekte",
    projectsText:
      "Von der Schülerhilfe über die Filmabende bis zum Fest der Begegnung – entdecken Sie, wie wir im Stadtteil wirken.",
    partnersKicker: "Partnerschaften",
    partnersTitle: "Gemeinsam stärker",
    partnersText:
      "Unsere Arbeit lebt von starken Partnerschaften – mit dem Bezirksamt Bergedorf, Fördern und Wohnen, KulturA und vielen weiteren Akteuren im Stadtteil.",
    ctaTitle: "Werden Sie Teil des Miteinanders",
    ctaText:
      "Ob als Mitglied, Ehrenamtliche:r, Mentor:in oder Förderer – jede Unterstützung macht unsere Arbeit im Stadtteil möglich.",
  },
  about: {
    kicker: "Über uns",
    title: "Ein Verein aus dem Stadtteil – für den Stadtteil",
    lead:
      "Miteinander in Bergedorf e.V. wurde 2014 von Anwohner:innen in Neuallermöhe gegründet – von Menschen, die selbst erlebt haben, was Ankommen bedeutet. Aus dieser Erfahrung entstand ein Verein, der Brücken baut: zwischen Kulturen, Generationen und Institutionen.",
    missionTitle: "Unsere Mission",
    missionText:
      "Wir stärken und fördern die Integration von Familien, Kindern und Jugendlichen unterschiedlicher Herkunft – mit besonderem Fokus auf afrikanische Communities in Bergedorf und Neuallermöhe. Unser Ziel ist ein respektvolles Miteinander, in dem alle Bewohner:innen gleichberechtigt am gesellschaftlichen Leben teilhaben: in Schule, Ausbildung, Beruf und Nachbarschaft.",
    missionBullets: [
      "Integration als gegenseitiger Prozess – beide Seiten gehen aufeinander zu",
      "Kinder, Jugendliche und Familien stehen im Mittelpunkt unserer Arbeit",
      "Besonderer Fokus auf afrikanische Communities in Bergedorf und Neuallermöhe",
      "Brücken bauen zwischen Kulturen, Generationen und Institutionen",
    ],
    charterTitle: "Charta der Vielfalt",
    charterText:
      "Miteinander in Bergedorf e.V. ist Unterzeichner der Charta der Vielfalt. Damit verpflichten wir uns zu einem vorurteilsfreien Arbeits- und Gesellschaftsumfeld und setzen uns aktiv für Wertschätzung und Respekt aller Menschen ein – unabhängig von Herkunft, Religion, Alter oder Geschlecht.",
    philosophyTitle: "Unsere Philosophie",
    philosophy: [
      "Wir verstehen Integration als einen gegenseitigen Prozess. Sie gelingt nur, wenn beide Seiten aufeinander zugehen – die Zugewanderten und die aufnehmende Gesellschaft.",
      "Menschen mit Migrationsgeschichte bringen Wissen, Sprachen und Erfahrungen mit. Diese Ressourcen sichtbar zu machen, statt nur Defizite zu verwalten, ist der Kern unserer Arbeit.",
      "Bildung ist der wichtigste Schlüssel zur Teilhabe. Deshalb liegt unser Schwerpunkt auf Kindern, Jugendlichen und ihren Familien.",
      "Wir arbeiten parteipolitisch und konfessionell unabhängig, ehrenamtlich getragen und eng vernetzt mit Schulen, Behörden und Initiativen in Bergedorf.",
    ],
    valuesTitle: "Unsere Werte",
    values: [
      { title: "Toleranz", text: "Wir begegnen allen Menschen mit Respekt und Offenheit – unabhängig von Herkunft, Religion oder Lebensweise." },
      { title: "Gegenseitiges Lernen", text: "Wir lernen voneinander: Sprache, Kultur, Alltag. Beide Seiten profitieren vom Austausch." },
      { title: "Begegnung", text: "Begegnung auf Augenhöhe baut Vorurteile ab und schafft Vertrauen zwischen Nachbar:innen." },
      { title: "Austausch", text: "Der Austausch zwischen afrikanischen und deutschen Bewohner:innen ist das Herz unserer Arbeit." },
    ],
    historyTitle: "Unsere Geschichte",
    history: [
      { year: "2014", title: "Gründung", text: "Anwohner:innen aus Neuallermöhe gründen den Verein, um Integration im Alltag konkret zu gestalten – mit Lernen, Festen und Begegnung." },
      { year: "2016", title: "Interkulturelle Filmabende", text: "Die ersten Filmabende in Neuallermöhe starten – bis heute eine der erfolgreichsten Veranstaltungsreihen des Vereins." },
      { year: "2019", title: "Charta der Vielfalt", text: "Der Verein unterzeichnet die Charta der Vielfalt und verpflichtet sich zu einem vorurteilsfreien Miteinander." },
      { year: "2021", title: "Feste der Begegnung", text: "Das interkulturelle Fest und die Nigeria Celebration etablieren sich als feste Termine im Stadtteilkalender." },
      { year: "2025", title: "Digitale Partnerschaft", text: "Mit HolyDigits101 startet die strategische Partnerschaft für digitale Bildung und Sichtbarkeit." },
    ],
    boardTitle: "Der Vorstand",
    boardText:
      "Ehrenamtlich, erfahren und tief im Stadtteil verwurzelt. Der Vorstand ist Ihr direkter Ansprechpartner für alles rund um den Verein.",
    board: [
      { name: "Henry Akanno", role: "Vorstand · 1. Vorsitzender", phone: org.boardPhone, text: "Ihr direkter Ansprechpartner für Projekte, Netzwerke, Presse und Mitgliedschaft." },
      { name: "Sarah Denis", role: "Stellvertretende Vorsitzende", phone: "", text: "Verantwortlich für Bildungsangebote, Familienarbeit und die Begleitung der Ehrenamtlichen." },
      { name: "Anyadike Chijioke", role: "Kassenwart", phone: "", text: "Finanzen, Mitgliederverwaltung und die Organisation der Veranstaltungen." },
    ],
  },
  projects: {
    kicker: "Projekte",
    title: "Was wir konkret tun",
    lead:
      "Unsere Projekte entstehen aus dem Bedarf im Stadtteil. Sie sind langfristig angelegt, ehrenamtlich getragen und offen für alle – von der Lernhilfe bis zum großen Fest.",
    items: [
      { slug: "filmabende", tag: "Kultur", title: "Interkulturelle Filmabende Neuallermöhe", text: "Unsere erfolgreichste Veranstaltungsreihe: Regelmäßige Filmabende mit Filmen aus Afrika, Europa und der ganzen Welt – gefolgt von moderierten Gesprächen. Die Abende sind regelmäßig sehr gut besucht und ziehen ein großes, buntes Publikum aus dem gesamten Stadtteil an.", img: "/images/intercultural.webp", content: ["We would like to present an international film in the main hall of the KulturA as part of a film evening. We cordially invite both the residents of Neuallermöhe and the residents of the refugee accommodation in Bergedorf-West. As part of the program, we will offer an international buffet consisting of food donations from local residents. Musical entertainment before the film will be provided by a student band from the Gymnasium Allermöhe. Admission is free. Cooperation partners are : Neuallermöhe district office, KulturA, Allermöhe Gymnasium, Bergedorf-West refugee accommodation, Bergedorf district office.Objectives:  The event aims to foster intercultural exchange between people and thus improve community relations. Furthermore, it seeks to enhance the image of the neighborhood.Target group:  Residents of Neuallermöhe, people with a migration background.When is the project scheduled to take place?:  November 20, 2015."] },
      { slug: "nachbarschaftshilfe", tag: "Begegnung", title: "Nachbarschaftshilfe", text: "Praktische Hilfe im Alltag: Unterstützung beim Einkauf, Begleitung zu Terminen, Hilfe bei Behördengängen und Anträgen sowie ein offenes Ohr für die Sorgen der Nachbar:innen. Nachbarschaftshilfe verbindet Menschen über Generationen und Herkunft hinweg.", img: "/images/community.jpg", content: ["Nachbarschaftshilfe ist gelebte Solidarität im Alltag. Wir unterstützen Nachbar:innen bei kleinen und größeren Aufgaben: beim Einkauf, bei der Begleitung zu Terminen, bei Behördengängen und beim Ausfüllen von Anträgen.", "Oft ist es schon ein offenes Ohr, das den Unterschied macht. Unsere Ehrenamtlichen hören zu, beraten und vermitteln – immer vertraulich und auf Augenhöhe.", "Die Nachbarschaftshilfe verbindet Menschen über Generationen und Herkunft hinweg. Wer Hilfe braucht oder helfen möchte, kann sich jederzeit an den Vorstand wenden."] },
      { slug: "integration", tag: "Integration", title: "Integration & Bildung für afrikanische Communities", text: "Gezielte Angebote für afrikanische Communities, Geflüchtete und Familien: Orientierung im neuen Alltag, Sprach- und Lernförderung sowie Beratung zu Schule, Ausbildung und Behördenthemen – immer auf Augenhöhe und mit viel Herz.", img: "/images/mentoring.jpg", content: ["Miteinander in Bergedorf e.V. setzt sich ein für die Stärkung und Förderung von Integration für Familien, Kinder und Jugendliche aus unterschiedlichen Herkunftsländern – mit besonderem Fokus auf afrikanische Communities in Bergedorf und Neuallermöhe.", "Wir bieten Orientierung im neuen Alltag: Sprach- und Lernförderung, Beratung zu Schule, Ausbildung und Behördenthemen sowie Unterstützung bei der Bewältigung von kleinen oder größeren Problemen des Alltags.", "Unser Ansatz ist die Hilfe zur Selbsthilfe. Menschen mit Migrationsgeschichte bringen Wissen, Sprachen und Erfahrungen mit – diese Ressourcen sichtbar zu machen, ist der Kern unserer Arbeit."] },
      { slug: "kinderfamilien", tag: "Familie", title: "Kinder- & Familienveranstaltungen", text: "Feste, Ferienaktionen und Familiennachmittage: Wir schaffen Räume, in denen Kinder spielen, lernen und Freundschaften schließen – und in denen Eltern sich kennenlernen und vernetzen können.", img: "/images/festival.jpg", content: ["Unsere Kinder- und Familienveranstaltungen schaffen Räume der Begegnung für den gesamten Stadtteil. Feste, Ferienaktionen und Familiennachmittage bringen Kinder zum Spielen, Lernen und Freundschaften schließen.", "Eltern haben die Gelegenheit, sich kennenzulernen, auszutauschen und zu vernetzen. Viele unserer Projekte sind aus solchen Begegnungen entstanden.", "Die Veranstaltungen sind generationsübergreifend und nicht konfessionsgebunden – offen für alle Menschen im Stadtteil."] },
      { slug: "mentoring", tag: "Bildung", title: "Schüler-Mentoring", text: "Jugendliche werden über einen längeren Zeitraum von erfahrenen Mentor:innen begleitet – beim Lernen, bei der Berufsorientierung und bei Fragen des Alltags. Ziel ist ein guter Schulabschluss und ein selbstbewusster Start ins Berufsleben.", img: "/images/mentoring.jpg", content: ["Im Rahmen des Mentorings übernehmen engagierte Hamburger:innen eine Art persönliche Patenschaft für Jugendliche oder Erwachsene mit Migrationshintergrund. Sie helfen ihnen bei der Bewältigung von kleinen oder größeren Problemen und stehen als Ansprechpartner:innen mit Rat und Tat zur Seite.", "Jede Mentoring-Beziehung ist anders. Sie hängt stark von dem Engagement, der Offenheit und der individuellen Lebenssituation der beteiligten Personen ab. Häufig hilft schon ein offenes Ohr oder die bessere Kenntnis der Lebensumstände in Deutschland, um den Mentees willkommene Unterstützung zu bieten.", "Wenn auch Sie Lust haben, sich an dem Mentoring-Programm zu beteiligen, melden Sie sich bitte bei uns. Wir führen sorgfältig ein und begleiten Sie während Ihrer gesamten Einsatzzeit."] },
      { slug: "schuelerhilfe", tag: "Bildung", title: "Schülerhilfe & Hausaufgabenbetreuung", text: "In kleinen Gruppen unterstützen wir Kinder der Grund- und Stadtteilschulen bei Hausaufgaben, Deutsch und Mathematik. Kostenfrei, wohnortnah und in enger Absprache mit den Eltern.", img: "/images/community.jpg", content: ["Jugendliche und Kinder mit oder ohne Migrationshintergrund haben es zumeist schwieriger in der Schule als andere. Wir versuchen, Kindern und Jugendlichen mit Nachhilfebedarf eine Nachhilfelehrerin oder einen Nachhilfelehrer zu vermitteln.", "Dabei bemühen wir uns im Sinne von „Hilfe zur Selbsthilfe“, Nachhilfelehrer:innen gerade auch aus unserem Migranten-Netzwerk zu rekrutieren. Denn was der eine nicht kann, kann der andere gerade besonders gut.", "In kleinen Gruppen unterstützen wir Kinder der Grund- und Stadtteilschulen bei Hausaufgaben, Deutsch und Mathematik – kostenfrei, wohnortnah und in enger Absprache mit den Eltern."] },
      { slug: "fest", tag: "Begegnung", title: "Interkulturelles Fest der Begegnung", text: "Einmal im Jahr wird der Stadtteil zur Bühne: Musik, Tanz, Küche und Gespräche aus vielen Ländern. Das Fest ist unser sichtbarstes Zeichen für ein offenes Bergedorf.", img: "/images/festival.jpg", content: ["Die meisten Bewohner der Asylbewerberunterkünfte haben wenig oder keinen Außenkontakt zu Bergedorfer:innen bzw. Hamburger:innen, vor allem jene, die erst kürzlich angekommen sind. Der Verein Miteinander in Bergedorf e.V. möchte ein Fest in Neuallermöhe veranstalten, zu dem gezielt die Bewohner der Asylbewerberunterkünfte in Bergedorf eingeladen werden.", "Viele Vereinsmitglieder haben ähnliche Migrations- und Fluchterfahrungen und können sich gut in die Lebenslage Asylsuchender hineinversetzen. Das Fest ist generationsübergreifend und nicht konfessionsgebunden.", "Das Festprogramm wird bestimmt von Musik, Tanz, Unterhaltungen sowie Essen und Trinken. Es wird mit einem Busunternehmen verhandelt, um einen unentgeltlichen Bus-Shuttle von und zu den Unterkünften anbieten zu können. Der Verein verhandelt mit Bergedorfer Geschäftsinhaber:innen, um durch Spenden kleine Geschenke für die teilnehmenden Kinder bereitstellen zu können."] },
      { slug: "nigeria", tag: "Kultur", title: "Nigeria Celebration", text: "Ein Fest der nigerianischen Community in Hamburg – mit Kultur, Kulinarik und Austausch. Es stärkt die Identität junger Menschen und öffnet zugleich die Türen für Nachbar:innen.", img: "/images/nigeria-anniversary.webp", content: ["Die Nigeria Celebration ist eine offene Veranstaltung der nigerianischen Community in Hamburg. Sie findet im KulturA statt und ist für alle Interessierten zugänglich.", "Das Fest feiert die Kultur, die Küche und die Traditionen Nigerias – und stärkt zugleich die Identität junger Menschen mit nigerianischen Wurzeln.", "Gleichzeitig öffnet die Veranstaltung die Türen für Nachbar:innen und alle, die die nigerianische Kultur kennenlernen möchten. Musik, Tanz, Kulinarik und Austausch stehen im Mittelpunkt."] },
    ],
    partnersKicker: "Kooperationspartner",
    partnersTitle: "Mit starken Partnern im Stadtteil",
    partnersText:
      "Unsere Projekte gelingen im engen Austausch mit verlässlichen Kooperationspartnern aus Politik, Sozialwirtschaft und Kultur:",
    partners: [
      "Bezirksamt Bergedorf",
      "Fördern und Wohnen (AWO)",
      "KulturA",
      "Kulturzentrum LOLA",
      "Charta der Vielfalt",
      "Schulen in Neuallermöhe",
    ],
  },
  news: {
    kicker: "Aktuelles & Termine",
    title: "Was gerade passiert",
    lead: "Neuigkeiten aus dem Verein, Berichte aus den Projekten und alle kommenden Termine auf einen Blick.",
    newsTitle: "Neuigkeiten",
    eventsTitle: "Kommende Termine",
    pressTitle: "Presse",
    pressText: "Über unsere Arbeit wurde unter anderem in der lokalen Presse berichtet. Für Presseanfragen und Bildmaterial wenden Sie sich bitte an den Vorstand.",
    readMore: "Weiterlesen",
    back: "Zurück zu Aktuelles & Termine",
    shareTitle: "Beitrag teilen",
    copied: "Link kopiert!",
    relatedNews: "Weitere Beiträge",
    relatedEvents: "Weitere Termine",
    authorLabel: "Von",
    readLabel: "Lesezeit",
    dateLabel: "Datum",
    timeLabel: "Uhrzeit",
    locationLabel: "Ort",
    detailsLabel: "Details ansehen",
    items: [
      {
        slug: "filmabend-ausgebucht",
        date: "12. Februar 2026",
        tag: "Bericht",
        author: "Der Vorstand",
        readTime: "3 Min.",
        title: "Filmabend in Neuallermöhe erneut ausgebucht",
        excerpt: "Über 70 Gäste diskutierten nach dem Film über Identität, Herkunft und Zugehörigkeit im Stadtteil – die Reihe bleibt ein voller Erfolg.",
        image: "/images/festival.webp",
        content: [
          "Am 10. Februar war es wieder so weit: Der interkulturelle Filmabend in Neuallermöhe war erneut ausgebucht. Über 70 Gäste aus dem gesamten Stadtteil kamen zusammen, um gemeinsam einen Film zu sehen, der die Frage nach Identität und Zugehörigkeit in den Mittelpunkt stellte.",
          "Nach der Vorführung moderierte der Vorstand eine lebhafte Diskussion. Viele Besucher:innen teilten persönliche Erfahrungen über das Ankommen in Deutschland, über Heimat und darüber, was es bedeutet, sich zugehörig zu fühlen. Genau diese Gespräche sind der eigentliche Kern unserer Filmabende: Film als Türöffner für einen ehrlichen Austausch zwischen Menschen, die sich sonst vielleicht nie begegnet wären.",
          "Wir danken allen Gästen, den Helfer:innen und unserem Kooperationspartner KulturA für einen wunderbaren Abend. Der nächste Filmabend findet am 28. März statt – sichern Sie sich rechtzeitig einen Platz.",
        ],
      },
      {
        slug: "fest-der-begegnung-2026",
        date: "3. Februar 2026",
        tag: "Ankündigung",
        author: "Der Vorstand",
        readTime: "2 Min.",
        title: "Save the Date: Interkulturelles Fest der Begegnung 2026",
        excerpt: "Am 13. Juni 2026 verwandelt sich Neuallermöhe wieder in eine Bühne der Kulturen – seien Sie dabei!",
        image: "/images/edel-motion.webp",
        content: [
          "Das Interkulturelle Fest der Begegnung 2026 findet am Samstag, den 13. Juni 2026, in Neuallermöhe statt. Von 12 bis 20 Uhr verwandelt sich der Stadtteil in eine Bühne der Kulturen.",
          "Musik und Tanz aus Afrika, Europa und der ganzen Welt, kulinarische Köstlichkeiten aus vielen Ländern, ein buntes Kinderprogramm und viel Raum für Gespräche – das Fest ist unser sichtbarstes Zeichen für ein offenes Bergedorf.",
          "Wir laden alle Vereine, Initiativen und Nachbar:innen ein, sich mit einem Stand oder Programmbeitrag zu beteiligen. Wer mitmachen möchte, meldet sich einfach beim Vorstand. Wir freuen uns auf Sie!",
        ],
      },
      {
        slug: "partnerschaft-holydigits101",
        date: "28. Januar 2026",
        tag: "Verein",
        author: "Henry Akanno",
        readTime: "3 Min.",
        title: "Strategische Partnerschaft mit HolyDigits101",
        excerpt: "Gemeinsam bauen wir digitale Bildungsangebote und die neue Online-Präsenz des Vereins auf.",
        image: "/images/community.jpg",
        content: [
          "Miteinander in Bergedorf e.V. freut sich über eine neue strategische Partnerschaft: Ab sofort arbeiten wir mit HolyDigits101 zusammen, einem Partner für Digitalisierung, digitale Bildung und moderne Kommunikation.",
          "Gemeinsam entwickeln wir digitale Lernformate für Jugendliche, modernisieren unsere Vereinsprozesse und machen die Arbeit des Vereins online sichtbar – dazu gehört auch der vollständige Relaunch unserer Website, den Sie gerade sehen.",
          "Die Partnerschaft folgt unserer Überzeugung, dass Integration und Teilhabe heute auch digitale Räume brauchen. Wer Zugang zu digitaler Bildung hat, hat bessere Chancen in Schule, Ausbildung und Beruf. Wir freuen uns auf die Zusammenarbeit und danken HolyDigits101 für das Vertrauen.",
        ],
      },
      {
        slug: "neue-lernwerkstatt",
        date: "20. Januar 2026",
        tag: "Bildung",
        author: "Sarah Denis",
        readTime: "2 Min.",
        title: "New open learning workshop coming soon in Neuallermöhe",
        excerpt: "Ab März 2026 bietet der Verein eine wöchentliche Lernwerkstatt für Schüler:innen an – kostenlos und ohne Anmeldung.",
        image: "/images/open-learning.png",
        content: [
          "A new open learning workshop will soon start at the Bürgerhaus Neuallermöhe. Every Saturday from 10 am to 1 pm, primary and secondary school students can receive free support with homework, German and mathematics – guided by our volunteers.The workshop is deliberately low-threshold: no registration, no costs, no hurdles – just drop by. We are looking for committed learning companions who would like to help shape the workshop. Interested people are warmly invited to contact the board.",
        ],
      },
      {
        slug: "mentoren-gesucht",
        date: "10. Januar 2026",
        tag: "Projekt",
        author: "Henry Akanno",
        readTime: "3 Min.",
        title: "Neue Mentor:innen und Ehrenamtliche gesucht",
        excerpt: "Für das laufende Schuljahr suchen wir engagierte Menschen, die Jugendliche begleiten oder in der Nachbarschaftshilfe mithelfen möchten.",
        image: "/images/mentoring.jpg",
        content: [
          "Für das laufende Schuljahr sucht Miteinander in Bergedorf e.V. neue Mentor:innen und Ehrenamtliche. Wir begleiten aktuell über 120 Kinder und Jugendliche in Neuallermöhe und Bergedorf – und die Nachfrage wächst weiter.",
          "Als Mentor:in begleiten Sie einen jungen Menschen über einen längeren Zeitraum: bei Hausaufgaben, bei der Berufsorientierung oder einfach als verlässliche Ansprechperson. Ehrenamtliche helfen zudem bei unseren Festen, Filmabenden und in der Nachbarschaftshilfe.",
          "Vorkenntnisse sind nicht erforderlich – wir führen sorgfältig ein, bieten Fortbildungen an und begleiten Sie während Ihrer gesamten Einsatzzeit. Auch wenige Stunden im Monat machen einen großen Unterschied. Melden Sie sich unter info@mib-ev.de oder telefonisch beim Vorstand.",
        ],
      },
      {
        slug: "weihnachtsfeier-2025",
        date: "18. Dezember 2025",
        tag: "Bericht",
        author: "Der Vorstand",
        readTime: "2 Min.",
        title: "Weihnachtsfeier der Familien in Neuallermöhe",
        excerpt: "Ein Nachmittag mit Musik, Essen und Geschenken für über 40 Kinder aus dem Stadtteil.",
        image: "/images/poster.webp",
        content: [
          "Am 13. Dezember feierte Miteinander in Bergedorf e.V. seine traditionelle Weihnachtsfeier für Familien in Neuallermöhe. Über 40 Kinder und ihre Eltern erlebten einen Nachmittag voller Musik, Spiel und Begegnung.",
          "Wochenlang hatten Ehrenamtliche geplant, gebacken und Geschenke gesammelt. Möglich wurde das Fest durch Spenden aus dem Stadtteil und die Unterstützung unserer Kooperationspartner.",
          "Für viele Familien ist die Weihnachtsfeier der Höhepunkt des Jahres – ein Ort, an dem Kinder lachen, Eltern sich austauschen und Gemeinschaft spürbar wird. Wir sagen Danke an alle, die diesen Tag möglich gemacht haben.",
        ],
      },
    ],
    events: [
      {
        slug: "lernwerkstatt-maerz",
        day: "14",
        month: "März",
        time: "10:00 – 13:00 Uhr",
        place: "Bürgerhaus Neuallermöhe",
        title: "Schülerhilfe – offene Lernwerkstatt",
        excerpt: "Kostenlose Lernunterstützung für Schüler:innen – ohne Anmeldung, einfach vorbeikommen.",
        image: "/images/community.jpg",
        content: [
          "Jeden Samstag von 10 bis 13 Uhr öffnet unsere offene Lernwerkstatt im Bürgerhaus Neuallermöhe ihre Türen. Schüler:innen der Grund- und Stadtteilschulen erhalten kostenlose Unterstützung bei Hausaufgaben, Deutsch und Mathematik.",
          "Unsere Ehrenamtlichen begleiten die Kinder in kleinen Gruppen und gehen individuell auf ihre Fragen ein. Eltern sind jederzeit willkommen, um sich auszutauschen oder selbst mitzuhelfen.",
          "Eine Anmeldung ist nicht erforderlich. Kommen Sie einfach vorbei – wir freuen uns auf Sie!",
        ],
      },
      {
        slug: "filmabend-maerz",
        day: "28",
        month: "März",
        time: "19:00 Uhr",
        place: "Neuallermöhe (Ort auf Anfrage)",
        title: "Interkultureller Filmabend",
        excerpt: "Film, Gespräch und Begegnung – der nächste Abend unserer erfolgreichen Reihe.",
        image: "/images/film.jpg",
        content: [
          "Der nächste interkulturelle Filmabend findet am 28. März um 19 Uhr in Neuallermöhe statt. Gezeigt wird ein Film, der zum Nachdenken anregt und den Blick auf andere Kulturen öffnet.",
          "Wie immer folgt auf den Film eine moderierte Diskussion. Hier kommen Menschen zusammen, die sich sonst vielleicht nie begegnet wären – das ist das Herz unserer Filmabende.",
          "Der Eintritt ist frei, um eine kleine Spende wird gebeten. Da die Plätze begrenzt sind, empfehlen wir eine frühzeitige Anmeldung beim Vorstand.",
        ],
      },
      {
        slug: "mitgliederversammlung-2026",
        day: "25",
        month: "April",
        time: "17:00 Uhr",
        place: "Weidenbaumsweg 54, Neuallermöhe",
        title: "Mitgliederversammlung 2026",
        excerpt: "Berichte, Wahlen und Ausblick – die jährliche Versammlung des Vereins.",
        image: "/images/hero.jpg",
        content: [
          "Am 25. April 2026 um 17 Uhr findet unsere jährliche Mitgliederversammlung in den Vereinsräumen am Weidenbaumsweg 54 statt.",
          "Auf der Tagesordnung stehen der Bericht des Vorstands, der Kassenbericht, der Ausblick auf die Projekte des Jahres sowie die Entlastung des Vorstands.",
          "Alle Mitglieder sind herzlich eingeladen. Auch Gäste, die sich für eine Mitgliedschaft interessieren, sind willkommen.",
        ],
      },
      {
        slug: "fest-der-begegnung-termin",
        day: "13",
        month: "Juni",
        time: "12:00 – 20:00 Uhr",
        place: "Neuallermöhe",
        title: "Interkulturelles Fest der Begegnung",
        excerpt: "Musik, Tanz, Küche und Gespräche aus vielen Ländern – das Fest des Jahres im Stadtteil.",
        image: "/images/festival.jpg",
        content: [
          "Am 13. Juni 2026 feiert der Stadtteil: Das Interkulturelle Fest der Begegnung verwandelt Neuallermöhe von 12 bis 20 Uhr in eine Bühne der Kulturen.",
          "Erwarten Sie Musik und Tanz aus Afrika, Europa und der ganzen Welt, kulinarische Köstlichkeiten, ein buntes Kinderprogramm und viele Gelegenheiten für Begegnung und Gespräch.",
          "Das Fest ist offen für alle – der Eintritt ist frei. Vereine und Initiativen, die sich mit einem Stand beteiligen möchten, melden sich bitte beim Vorstand.",
        ],
      },
    ],
  },
  involved: {
    kicker: "Mitmachen",
    title: "Es braucht viele Hände für ein gutes Miteinander",
    lead: "Ob Zeit, Wissen oder finanzielle Unterstützung – es gibt viele Wege, unsere Arbeit im Stadtteil möglich zu machen.",
    ways: [
      { icon: "heart", title: "Mitglied werden", text: "Als Mitglied stärken Sie den Verein langfristig und gestalten unsere Arbeit in der Mitgliederversammlung aktiv mit. Der Antrag ist unkompliziert – wir beraten Sie gerne persönlich.", cta: "Mitgliedsantrag anfragen" },
      { icon: "hands", title: "Ehrenamt & Mentoring", text: "Begleiten Sie Kinder bei den Hausaufgaben, werden Sie Mentor:in oder helfen Sie bei Festen, Filmabenden und in der Nachbarschaftshilfe.", cta: "Ehrenamt anfragen" },
      { icon: "gift", title: "Spenden", text: "Mit einer Spende finanzieren Sie Lernmaterial, Räume und Veranstaltungen. Der Verein ist als gemeinnützig anerkannt – Spendenbescheinigungen stellen wir gerne aus.", cta: "Spendenkonto ansehen" },
      { icon: "briefcase", title: "Als Unternehmen fördern", text: "Unterstützen Sie ein konkretes Projekt, stellen Sie Praktikumsplätze bereit oder werden Sie Kooperationspartner.", cta: "Kooperation besprechen" },
    ],
    stepsTitle: "So werden Sie Mitglied",
    stepsText: "In drei einfachen Schritten sind Sie Teil des Miteinanders – ohne bürokratische Hürden.",
    steps: [
      { title: "Kontakt aufnehmen", text: "Schreiben Sie uns oder rufen Sie den Vorstand direkt an – wir beantworten gerne alle Fragen." },
      { title: "Antrag ausfüllen", text: "Der Mitgliedsantrag ist in wenigen Minuten ausgefüllt. Der Jahresbeitrag ist bewusst niedrig gehalten." },
      { title: "Willkommen im Verein", text: "Sie erhalten alle Infos zu Projekten, Terminen und zur Mitgliederversammlung – und sind herzlich willkommen." },
    ],
    donateTitle: "Jetzt spenden",
    donateText:
      "Miteinander in Bergedorf e.V. ist als gemeinnützig anerkannt. Ihre Spende ist steuerlich absetzbar – auf Wunsch stellen wir eine Spendenbescheinigung aus. Jeder Beitrag kommt direkt den Projekten im Stadtteil zugute.",
    donateCta: "Jetzt spenden",
    accountHolder: "Kontoinhaber",
    fundraisingTitle: "Charity Shop & Fundraising",
    fundraisingText:
      "Neben direkten Spenden sammeln wir auf vielfältige Weise: mit Flohmärkten, Benefiz-Essen und Verkaufsständen beim Fest der Begegnung sowie über unseren Charity Shop. Sachspenden nehmen wir nach Absprache gerne entgegen. Jeder Euro fließt direkt in unsere Projekte.",
    volunteerTitle: "Was Ehrenamtliche bei uns erwartet",
    volunteerPoints: [
      "Eine feste Ansprechperson und eine sorgfältige Einführung",
      "Flexible Einsatzzeiten – auch wenige Stunden im Monat helfen",
      "Fortbildungen zu interkultureller Kompetenz und Lernbegleitung",
      "Ein herzliches Team und ein echter Einblick in den Stadtteil",
    ],
  },
  partners: {
    kicker: "Partner & Netzwerk",
    title: "Starke Partnerschaften für ein offenes Bergedorf",
    lead: "Wir arbeiten eng mit Institutionen, Initiativen und Unternehmen zusammen, die unsere Haltung teilen.",
    strategicKicker: "Strategischer Partner",
    hdTitle: "HolyDigits101",
    hdText:
      "HolyDigits101 ist unser strategischer Partner für Digitalisierung, digitale Bildung und Kommunikation. Gemeinsam entwickeln wir digitale Lernformate für Jugendliche, modernisieren die Vereinsprozesse und machen die Arbeit von Miteinander in Bergedorf e.V. online sichtbar.",
    hdPoints: [
      "Digitale Bildungs- und Medienworkshops für Jugendliche",
      "Website, Design und digitale Kommunikation des Vereins",
      "Beratung zu Datenschutz, Tools und digitalen Prozessen",
    ],
    hdCta: "holydigits101.com besuchen",
    othersTitle: "Weitere Partner & Netzwerke",
    others: [
      { name: "Bezirksamt Bergedorf", text: "Zusammenarbeit bei Stadtteilentwicklung, Integrationsarbeit und Förderprogrammen." },
      { name: "Fördern und Wohnen (AWO)", text: "Kooperation bei sozialer Teilhabe, Wohnraumberatung und Unterstützung für Familien." },
      { name: "KulturA", text: "Gemeinsame kulturelle Projekte und Veranstaltungen für den Stadtteil." },
      { name: "Kulturzentrum LOLA", text: "Gemeinsamer Veranstaltungsort für Filmabende und kulturelle Formate in Bergedorf." },
      { name: "Charta der Vielfalt", text: "Als Unterzeichner setzen wir uns für ein Arbeits- und Gesellschaftsumfeld frei von Vorurteilen ein." },
      { name: "Schulen in Neuallermöhe", text: "Enge Kooperation mit Grund- und Stadtteilschulen bei Lernförderung und Elternarbeit." },
    ],
    becomeTitle: "Partner werden",
    becomeText: "Sie möchten mit uns kooperieren oder ein Projekt fördern? Wir freuen uns auf Ihre Nachricht.",
  },
  contact: {
    kicker: "Kontakt & Impressum",
    title: "Sprechen Sie uns an",
    lead: "Wir freuen uns über Fragen, Ideen und Kooperationsanfragen – schreiben Sie uns, rufen Sie an oder kommen Sie vorbei.",
    formTitle: "Nachricht senden",
    form: { name: "Name", email: "E-Mail", subject: "Betreff", message: "Ihre Nachricht", send: "Nachricht senden", sent: "Vielen Dank! Ihre Nachricht wurde vorbereitet." },
    infoTitle: "Kontaktdaten",
    hoursTitle: "Sprechzeiten",
    hours: ["Dienstag: 15:00 – 18:00 Uhr", "Donnerstag: 15:00 – 18:00 Uhr", "sowie nach Vereinbarung"],
    donateCta: "Jetzt spenden",
    imprintTitle: "Impressum",
    imprintBlocks: [
      { title: "Angaben gemäß § 5 TMG", lines: ["Miteinander in Bergedorf e.V.", "Weidenbaumsweg 54", "21035 Hamburg", "Deutschland", "Postfach 808115 · 21015 Hamburg"] },
      { title: "Vertreten durch", lines: ["Henry Akanno (Vorstand)", "Telefon: 0174 1349 339"] },
      { title: "Registereintrag", lines: ["Eingetragen im Vereinsregister", "Amtsgericht Hamburg", "Registernummer: VR 22314"] },
      { title: "Umsatzsteuer", lines: ["USt-IdNr.: 17/451/08764"] },
      { title: "Kontakt", lines: ["Telefon: 040 4608 2222", "E-Mail: info@mib-ev.de", "Web: www.mib-ev.de"] },
    ],
    nonProfitTitle: "Gemeinnützigkeit",
    nonProfitText:
      "Miteinander in Bergedorf e.V. verfolgt ausschließlich und unmittelbar gemeinnützige Zwecke im Sinne des Abschnitts „Steuerbegünstigte Zwecke“ der Abgabenordnung. Der Verein ist durch das zuständige Finanzamt als gemeinnützig anerkannt. Spenden sind steuerlich absetzbar; auf Wunsch stellen wir eine Zuwendungsbescheinigung (Spendenbescheinigung) aus.",
    legalTitle: "Rechtliche Hinweise",
    legal: [
      {
        title: "Haftung für Inhalte",
        text: "Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs. 1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.",
      },
      {
        title: "Haftung für Links",
        text: "Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft; rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.",
      },
      {
        title: "Urheberrecht",
        text: "Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.",
      },
      {
        title: "Datenschutz (Datenschutzerklärung)",
        text: "Die Nutzung unserer Website ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (z. B. Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies stets auf freiwilliger Basis und ausschließlich zur Bearbeitung Ihrer Anfrage. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. Wir weisen darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann; ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich. Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen.",
      },
      {
        title: "Datenschutz und Mitglieder",
        text: "Die Daten unserer Mitglieder (Name, Anschrift, Kontaktdaten, Beitragsdaten) werden ausschließlich für die Vereinsverwaltung im Rahmen der Mitgliedschaft gespeichert und verarbeitet. Eine Weitergabe an Dritte erfolgt nicht, sofern dies nicht gesetzlich vorgeschrieben oder zur Erfüllung satzungsgemäßer Aufgaben erforderlich ist. Mitglieder können jederzeit Auskunft über ihre gespeicherten Daten verlangen sowie deren Berichtigung oder Löschung beantragen. Bei Fragen zum Datenschutz wenden Sie sich bitte an den Vorstand.",
      },
    ],
  },
  footer: {
    about: "Gemeinnütziger Verein für Integration, Bildung und interkulturelle Begegnung in Hamburg-Bergedorf und Neuallermöhe – gegründet 2014.",
    nav: "Navigation",
    contact: "Kontakt",
    partner: "Strategischer Partner",
    rights: "Alle Rechte vorbehalten.",
    imprint: "Impressum & Datenschutz",
    madeWith: "Digitale Umsetzung in Partnerschaft mit",
  },
};

const en: typeof de = {
  cta: {
    primary: "Explore our projects",
    secondary: "Get involved & support",
    donate: "Donate now",
    contact: "Get in touch",
    more: "Learn more",
    all: "View all",
    membership: "Become a member",
    volunteer: "Volunteer",
  },
  home: {
    kicker: "Integration · Education · Encounter in Hamburg-Bergedorf",
    title: "Living together.\nBuilding together.",
    lead:
      "We strengthen the integration of families, children and young people from different backgrounds – with a special focus on African communities in Bergedorf and Neuallermöhe. Through encounter, education and mutual learning we create a neighbourhood where everyone feels they belong.",
    statsTitle: "Rooted in the neighbourhood since 2014",
    stats: [
      { value: "2014", label: "founded by local residents in Neuallermöhe" },
      { value: "8+", label: "ongoing projects & formats" },
      { value: "120+", label: "children & youth supported" },
      { value: "20+", label: "active volunteers" },
    ],
    missionKicker: "Our mission",
    missionTitle: "Encounter creates belonging",
    missionText:
      "Integration succeeds where people meet, listen to each other and build something together. Miteinander in Bergedorf e.V. is a place for education, culture and participation – open to everyone in the neighbourhood, regardless of origin, religion or language. Our special focus lies on the African communities in Bergedorf and Neuallermöhe.",
    pillars: [
      { icon: "book", title: "Education & support", text: "Homework help, mentoring and guidance – so young people can truly seize their opportunities." },
      { icon: "globe", title: "Intercultural dialogue", text: "Film evenings, festivals and conversations that break down prejudice and bring neighbours together." },
      { icon: "hands", title: "Participation & empowerment", text: "We accompany families in everyday life, with authorities and on their way into training and work." },
    ],
    projectsKicker: "Our work",
    projectsTitle: "Our key projects",
    projectsText:
      "From homework support and film evenings to the festival of encounter – discover how we make a difference in the neighbourhood.",
    partnersKicker: "Partnerships",
    partnersTitle: "Stronger together",
    partnersText:
      "Our work thrives on strong partnerships – with Bezirksamt Bergedorf, Fördern und Wohnen, KulturA and many other local actors.",
    ctaTitle: "Become part of the Miteinander",
    ctaText: "As a member, volunteer, mentor or supporter – every contribution makes our work in the neighbourhood possible.",
  },
  about: {
    kicker: "About us",
    title: "An association from the neighbourhood – for the neighbourhood",
    lead:
      "Miteinander in Bergedorf e.V. was founded in 2014 by local residents in Neuallermöhe – people who know first-hand what arriving in a new country means. From that experience grew an association that builds bridges: between cultures, generations and institutions.",
    missionTitle: "Our mission",
    missionText:
      "We strengthen and promote the integration of families, children and young people from different backgrounds – with a special focus on African communities in Bergedorf and Neuallermöhe. Our goal is a respectful togetherness in which all residents participate equally in social life: in school, training, work and neighbourhood.",
    missionBullets: [
      "Integration as a mutual process – both sides move towards each other",
      "Children, young people and families are at the heart of our work",
      "Special focus on African communities in Bergedorf and Neuallermöhe",
      "Building bridges between cultures, generations and institutions",
    ],
    charterTitle: "Charta der Vielfalt",
    charterText:
      "Miteinander in Bergedorf e.V. is a signatory of the German Diversity Charter. We thereby commit to a working and social environment free of prejudice and actively advocate for appreciation and respect for all people – regardless of origin, religion, age or gender.",
    philosophyTitle: "Our philosophy",
    philosophy: [
      "We understand integration as a mutual process. It only succeeds when both sides move towards each other – newcomers and the receiving society.",
      "People with a migration history bring knowledge, languages and experience. Making these resources visible, instead of only managing deficits, is at the core of our work.",
      "Education is the most important key to participation. That is why we focus on children, young people and their families.",
      "We work independently of political parties and religious denominations, carried by volunteers and closely networked with schools, authorities and initiatives in Bergedorf.",
    ],
    valuesTitle: "Our values",
    values: [
      { title: "Tolerance", text: "We meet all people with respect and openness – regardless of origin, religion or way of life." },
      { title: "Mutual learning", text: "We learn from each other: language, culture, everyday life. Both sides benefit from the exchange." },
      { title: "Encounter", text: "Encounter on equal terms breaks down prejudice and builds trust between neighbours." },
      { title: "Exchange", text: "The exchange between African and German residents is the heart of our work." },
    ],
    historyTitle: "Our story",
    history: [
      { year: "2014", title: "Foundation", text: "Local residents from Neuallermöhe found the association to shape integration in everyday life – with learning, festivals and encounter." },
      { year: "2016", title: "Intercultural film evenings", text: "The first film evenings in Neuallermöhe begin – to this day one of the association's most successful series." },
      { year: "2019", title: "Charta der Vielfalt", text: "The association signs the German Diversity Charter and commits to a prejudice-free togetherness." },
      { year: "2021", title: "Festivals of encounter", text: "The intercultural festival and Nigeria Celebration become fixed dates in the neighbourhood calendar." },
      { year: "2025", title: "Digital partnership", text: "The strategic partnership with HolyDigits101 for digital education and visibility begins." },
    ],
    boardTitle: "The board",
    boardText: "Voluntary, experienced and deeply rooted in the district. The board is your direct contact for everything concerning the association.",
    board: [
      { name: "Henry Akanno", role: "Board · Chairman", phone: org.boardPhone, text: "Your direct contact for projects, networks, press and membership." },
      { name: "Sarah Denis", role: "Vice-chairwoman", phone: "", text: "Responsible for educational offers, family work and supporting the volunteers." },
      { name: "Anyadike Chijioke", role: "Treasurer", phone: "", text: "Finances, membership administration and event organisation." },
    ],
  },
  projects: {
    kicker: "Projects",
    title: "What we actually do",
    lead:
      "Our projects grow out of real needs in the neighbourhood. They are long-term, volunteer-led and open to everyone – from learning support to the big festival.",
    items: [
      { slug: "filmabende", tag: "Culture", title: "Intercultural film evenings Neuallermöhe", text: "Our most successful series: regular film evenings with films from Africa, Europe and around the world – followed by moderated conversations. The evenings are consistently well attended and draw a large, diverse audience from across the district.", img: "/images/intercultural.webp", content: ["We would like to show an international film in the large hall of KulturA as part of a film evening. We warmly invite both the residents of Neuallermöhe and the residents of the refugee accommodation in Bergedorf-West.", "As a supporting programme we would like to offer an international buffet made up of food donations from local residents. The musical entertainment before the film will be provided by a school band from Gymnasium Allermöhe.", "Admission is free. After the screening there will be a moderated discussion where people from different cultures can meet and exchange ideas – that is the true core of our film evenings."] },
      { slug: "nachbarschaftshilfe", tag: "Encounter", title: "Neighbourhood support", text: "Practical everyday help: support with shopping, accompaniment to appointments, help with authorities and applications, and an open ear for neighbours' concerns. Neighbourhood support connects people across generations and origins.", img: "/images/community.jpg", content: ["Neighbourhood support is lived solidarity in everyday life. We support neighbours with small and larger tasks: shopping, accompaniment to appointments, dealing with authorities and filling in applications.", "Often it is simply an open ear that makes the difference. Our volunteers listen, advise and mediate – always confidential and on equal terms.", "Neighbourhood support connects people across generations and origins. Anyone who needs help or wants to help can contact the board at any time."] },
      { slug: "integration", tag: "Integration", title: "Integration & education for African communities", text: "Targeted offers for African communities, refugees and families: orientation in everyday life, language and learning support, and advice on school, training and authority matters – always on equal terms and with heart.", img: "/images/mentoring.jpg", content: ["Miteinander in Bergedorf e.V. is committed to strengthening and promoting integration for families, children and young people from different countries of origin – with a special focus on African communities in Bergedorf and Neuallermöhe.", "We offer orientation in everyday life: language and learning support, advice on school, training and authority matters, and support in dealing with small or larger everyday problems.", "Our approach is help for self-help. People with a migration history bring knowledge, languages and experience – making these resources visible is at the core of our work."] },
      { slug: "kinderfamilien", tag: "Family", title: "Children's & family events", text: "Festivals, holiday activities and family afternoons: we create spaces where children can play, learn and make friends – and where parents can meet and connect.", img: "/images/festival.jpg", content: ["Our children's and family events create spaces of encounter for the whole district. Festivals, holiday activities and family afternoons bring children together to play, learn and make friends.", "Parents have the opportunity to get to know each other, exchange ideas and network. Many of our projects have grown out of such encounters.", "The events are intergenerational and not tied to any denomination – open to all people in the district."] },
      { slug: "mentoring", tag: "Education", title: "Student mentoring", text: "Young people are accompanied over a longer period by experienced mentors – in learning, career orientation and everyday questions. The goal: a good school degree and a confident start into working life.", img: "/images/mentoring.jpg", content: ["As part of the mentoring programme, committed Hamburg residents take on a kind of personal sponsorship for young people or adults with a migration background. They help them deal with small or larger problems and are available as contact persons with advice and support.", "Every mentoring relationship is different. It depends heavily on the commitment, openness and individual life situation of the people involved. Often an open ear or better knowledge of living conditions in Germany is enough to offer mentees welcome support.", "If you would like to take part in the mentoring programme, please contact us. We will carefully introduce you and support you throughout your time."] },
      { slug: "schuelerhilfe", tag: "Education", title: "Homework & learning support", text: "In small groups we support primary and secondary school children with homework, German and mathematics. Free of charge, close to home and in close contact with parents.", img: "/images/community.jpg", content: ["Young people and children with or without a migration background often find school more difficult than others. We try to arrange a tutor for children and young people who need extra help.", "In the spirit of 'help for self-help', we endeavour to recruit tutors in particular from our migrant network. For what one person cannot do, another can do particularly well.", "In small groups we support primary and secondary school children with homework, German and mathematics – free of charge, close to home and in close contact with parents."] },
      { slug: "fest", tag: "Encounter", title: "Intercultural festival of encounter", text: "Once a year the district becomes a stage: music, dance, food and conversation from many countries. The festival is our most visible sign of an open Bergedorf.", img: "/images/festival.jpg", content: ["Most residents of the asylum accommodation have little or no contact with people from Bergedorf or Hamburg, especially those who have only recently arrived. The association Miteinander in Bergedorf e.V. would like to organise a festival in Neuallermöhe to which residents of the asylum accommodation in Bergedorf are specifically invited.", "Many association members have similar migration and flight experiences and can easily empathise with the situation of asylum seekers. The festival is intergenerational and not tied to any denomination.", "The festival programme will be determined by music, dance, entertainment as well as food and drink. Negotiations are underway with a bus company to offer a free shuttle to and from the accommodation. The association is negotiating with Bergedorf shop owners to provide small gifts for the participating children through donations."] },
      { slug: "nigeria", tag: "Culture", title: "Nigeria Celebration", text: "A celebration of the Nigerian community in Hamburg – with culture, cuisine and exchange. It strengthens the identity of young people and opens doors to neighbours.", img: "/images/nigeria-anniversary.webp", content: ["The Nigeria Celebration is an open event of the Nigerian community in Hamburg. It takes place at KulturA and is accessible to all interested people.", "The festival celebrates the culture, cuisine and traditions of Nigeria – and strengthens the identity of young people with Nigerian roots.", "At the same time, the event opens doors for neighbours and everyone who wants to learn about Nigerian culture. Music, dance, culinary delights and exchange are at the centre."] },
    ],
    partnersKicker: "Cooperation partners",
    partnersTitle: "Strong partners in the neighbourhood",
    partnersText: "Our projects succeed in close exchange with reliable cooperation partners from politics, social services and culture:",
    partners: [
      "Bezirksamt Bergedorf",
      "Fördern und Wohnen (AWO)",
      "KulturA",
      "LOLA cultural centre",
      "Charta der Vielfalt",
      "Schools in Neuallermöhe",
    ],
  },
  news: {
    kicker: "News & events",
    title: "What is happening now",
    lead: "News from the association, reports from our projects and all upcoming dates at a glance.",
    newsTitle: "Latest news",
    eventsTitle: "Upcoming events",
    pressTitle: "Press",
    pressText: "Our work has been covered by the local press. For press enquiries and image material please contact the board.",
    readMore: "Read more",
    back: "Back to news & events",
    shareTitle: "Share this post",
    copied: "Link copied!",
    relatedNews: "More articles",
    relatedEvents: "More events",
    authorLabel: "By",
    readLabel: "Reading time",
    dateLabel: "Date",
    timeLabel: "Time",
    locationLabel: "Location",
    detailsLabel: "View details",
    items: [
      {
        slug: "filmabend-ausgebucht",
        date: "12 February 2026",
        tag: "Report",
        author: "The board",
        readTime: "3 min",
        title: "Film evening in Neuallermöhe sold out again",
        excerpt: "More than 70 guests discussed identity, origin and belonging in the district after the screening – the series remains a great success.",
        image: "/images/festival.webp",
        content: [
          "The intercultural film evening in Neuallermöhe was once again a complete success for this year – it was a really great evening with about 150 participants.",
          "Our thanks go to the Bergedorf district office, F&W – fördern und wohnen, the Alevi Cultural Center Bergedorf e.V. (BAKM e.V.), KulturA, the International Federation, the Neuallermöhe neighborhood office, the Allermöhe Gymnasium, and all of you!!! Thank you!",
          "More photos from the event can be found here: https://www.flickr.com/photos/mib-ev/sets/72157674202968714/.",
      ],
      },
      // {
      //   slug: "filmabend-ausgebucht",
      //   date: "12 February 2026",
      //   tag: "Report",
      //   author: "The board",
      //   readTime: "3 min",
      //   title: "Film evening in Neuallermöhe sold out again",
      //   excerpt: "More than 70 guests discussed identity, origin and belonging in the district after the screening – the series remains a great success.",
      //   image: "/images/festival.webp",
      //   content: [
      //     "The intercultural film evening in Neuallermöhe was once again a complete success for this year – it was a really great evening with about 150 participants.",
      //     "Our thanks go to the Bergedorf district office, F&W –fordern und wohnen, the Alevi Cultural Center Bergedorf eV (BAKM eV), KulturA, the International Federation, the Neuallermöhe neighborhood office, the Allermöhe Gymnasium, and all of you!!! Thank you! More photos from the event can be found here: https://www.flickr.com/photos/mib-ev/sets/72157674202968714/.",
          

      //   ],
        
      // },
      {
        slug: "fest-der-begegnung-2026",
        date: "3 February 2026",
        tag: "Announcement",
        author: "The board",
        readTime: "2 min",
        title: "Edel Motion deserves high praise!",
        excerpt: " ",
        image: "/images/edel-motion.webp",
        content: [
          "A big thank you and congratulations from Edel Motion. The DVD label Edel:Motion is a division of Edel Germany GmbH, a subsidiary of the publicly listed Edel AG, Europe's largest independent record company.",
          "Edel:Motion is distinguished primarily by its diverse selection of international DVD productions in the areas of special interest (wellness/fitness), film, television, and documentaries. Its mainstay is television formats, such as the crime series 'INSPECTOR BARNABY,' 'KOMMISSARIN LUND,' 'THE INSPECTOR LYNLEY MYSTERIES,'and 'THE INSPECTOR LYNLEY MYSTERIES,' which aired on ZDF. So, thank you very much from us too – Miteinander in Brgedorf eV. We were all very pleased with the extraordinary praise for the film evenings project and thank you very much for it. ",
        ],
      },
      {
        slug: "partnerschaft-holydigits101",
        date: "28 January 2026",
        tag: "Association",
        author: "Henry Akanno",
        readTime: "3 min",
        title: "Strategic partnership with HolyDigits101",
        excerpt: "Together we are building digital education formats and the new online presence of the association.",
        image: "/images/community.jpg",
        content: [
          "Miteinander in Bergedorf e.V. is delighted about a new strategic partnership: from now on we work with HolyDigits101, a partner for digitalisation, digital education and modern communication.",
          "Together we are developing digital learning formats for young people, modernising our association processes and making the association's work visible online – including the complete relaunch of our website, which you are looking at right now.",
          "The partnership follows our conviction that integration and participation today also need digital spaces. Those with access to digital education have better chances in school, training and work. We look forward to the collaboration and thank HolyDigits101 for their trust.",
        ],
      },
      {
        slug: "neue-lernwerkstatt",
        date: "20 January 2026",
        tag: "Education",
        author: "Sarah Denis",
        readTime: "2 min",
        title: "New open learning workshop starts in Neuallermöhe",
        excerpt: "From March 2026 the association offers a weekly learning workshop for students – free of charge and without registration.",
        image: "/images/open-learning.png",
        content: [
          "From March 2026 our open learning workshop will start at the Bürgerhaus Neuallermöhe. Every Saturday from 10 am to 1 pm, primary and secondary school students can learn for free – supported by our volunteers.",
          "The focus is on homework, German and mathematics. The workshop is deliberately low-threshold: no registration, no costs, no hurdles – just drop by.",
          "We are still looking for committed learning companions to help shape the workshop. Interested people are welcome to contact the board.",
        ],
      },
      {
        slug: "mentoren-gesucht",
        date: "10 January 2026",
        tag: "Project",
        author: "Henry Akanno",
        readTime: "3 min",
        title: "New mentors and volunteers wanted",
        excerpt: "For the current school year we are looking for committed people to accompany young people or support neighbourhood help.",
        image: "/images/mentoring.jpg",
        content: [
          "For the current school year, Miteinander in Bergedorf e.V. is looking for new mentors and volunteers. We currently accompany more than 120 children and young people in Neuallermöhe and Bergedorf – and demand keeps growing.",
          "As a mentor you accompany a young person over a longer period: with homework, career orientation or simply as a reliable contact person. Volunteers also help at our festivals, film evenings and in neighbourhood support.",
          "No previous knowledge is required – we provide a careful introduction, offer training and support you throughout your time. Even a few hours a month make a big difference. Contact us at info@mib-ev.de or by phone via the board.",
        ],
      },
      {
        slug: "weihnachtsfeier-2025",
        date: "18 December 2025",
        tag: "Report",
        author: "The board",
        readTime: "2 min",
        title: "We say thank you to our previous sponsors are the best!",
        excerpt: "Our first official thanks go to the Bergedorf district office.",
        image: "/images/poster.webp",
        content: [
          "Thank you, thank you! It's just after Christmas, and we've barely had a chance to enjoy any of the leisure activities. Our little 'projects' have evolved into a full-fledged year-round event. For every idea we realize, two new ones emerge. And that feels great, but it wouldn't be possible without a lot of outside help. We think it's time to say a quick thank you.",
          "First of all, we want to thank everyone who has participated with us so far. It's truly wonderful. You've given us so many great ideas. None of this would be possible without you! Thank you.",
          "Our first official thanks go to the Bergedorf district office.We didn't expect to receive so much appreciation and support. The bureaucratic processes involved are really manageable, and we now even enjoy calling them when we have questions, or simply dropping by to say hello. Therefore, we would like to thank all the staff at the Bergedorf district office. A big thank you to our main sponsors and supporters we have been able to attract so far! Not only through financial support, but also through many helpful tips and, of course, your constant presence for us. You are wonderful partners for us and we thank you. Thank you: (in chronological order) Free and Hanseatic City of Hamburg , Bergedorf District Office Promoting and Housing,  Neu Allermöhe District Advisory Board State Integration Advisory Board Integration Council, Bergedorf District Office Buhck Foundation House in the Park FoundationBergedorf, Bille Foundation Allermöhe Grammar School Edekan ,Think-Big Aktivoli ,volunteer exchange KulturA ,Allermöhe Bergedorfer, Zeitung Bille Weekly Newspaper Hamburg Police Gooding.de Google for NonprofitsDiversity Charter Festeburg Of course, these are far from all those we have to thank – we apologize in advance to everyone we have forgotten and ask for a brief message – we will of course add them later..",
        ],
      },
    ],
    events: [
      {
        slug: "lernwerkstatt-maerz",
        day: "14",
        month: "March",
        time: "10:00 – 13:00",
        place: "Bürgerhaus Neuallermöhe",
        title: "Learning workshop – open homework help",
        excerpt: "Free learning support for students – no registration, just drop by.",
        image: "/images/community.jpg",
        content: [
          "Every Saturday from 10 am to 1 pm our open learning workshop at the Bürgerhaus Neuallermöhe opens its doors. Primary and secondary school students receive free support with homework, German and mathematics.",
          "Our volunteers accompany the children in small groups and respond individually to their questions. Parents are always welcome to exchange ideas or help out themselves.",
          "No registration is required. Just come by – we look forward to seeing you!",
        ],
      },
      {
        slug: "filmabend-maerz",
        day: "28",
        month: "March",
        time: "19:00",
        place: "Neuallermöhe (venue on request)",
        title: "Intercultural film evening",
        excerpt: "Film, conversation and encounter – the next evening of our successful series.",
        image: "/images/film.jpg",
        content: [
          "The next intercultural film evening takes place on 28 March at 7 pm in Neuallermöhe. We will screen a film that makes you think and opens the view to other cultures.",
          "As always, a moderated discussion follows the film. This is where people come together who might otherwise never meet – that is the heart of our film evenings.",
          "Admission is free; a small donation is appreciated. As seats are limited, we recommend registering early via the board.",
        ],
      },
      {
        slug: "mitgliederversammlung-2026",
        day: "25",
        month: "April",
        time: "17:00",
        place: "Weidenbaumsweg 54, Neuallermöhe",
        title: "General members' assembly 2026",
        excerpt: "Reports, elections and outlook – the association's annual meeting.",
        image: "/images/hero.jpg",
        content: [
          "On 25 April 2026 at 5 pm our annual general members' assembly takes place in the association rooms at Weidenbaumsweg 54.",
          "The agenda includes the board's report, the treasurer's report, the outlook for the year's projects and the discharge of the board.",
          "All members are warmly invited. Guests interested in membership are also welcome.",
        ],
      },
      {
        slug: "fest-der-begegnung-termin",
        day: "13",
        month: "June",
        time: "12:00 – 20:00",
        place: "Neuallermöhe",
        title: "Intercultural Festival of Encounter",
        excerpt: "Music, dance, food and conversation from many countries – the district's event of the year.",
        image: "/images/festival.jpg",
        content: [
          "On 13 June 2026 the district celebrates: the Intercultural Festival of Encounter turns Neuallermöhe into a stage of cultures from 12 noon to 8 pm.",
          "Expect music and dance from Africa, Europe and around the world, culinary delights, a colourful children's programme and plenty of opportunities for encounter and conversation.",
          "The festival is open to everyone – admission is free. Associations and initiatives that would like to take part with a stall should contact the board.",
        ],
      },
    ],
  },
  involved: {
    kicker: "Get involved",
    title: "It takes many hands to build a good togetherness",
    lead: "Whether time, knowledge or financial support – there are many ways to make our work in the neighbourhood possible.",
    ways: [
      { icon: "heart", title: "Become a member", text: "As a member you strengthen the association long-term and help shape our work in the general assembly. The application is simple – we are happy to advise you personally.", cta: "Request membership form" },
      { icon: "hands", title: "Volunteering & mentoring", text: "Help children with homework, become a mentor or support festivals, film evenings and neighbourhood help.", cta: "Ask about volunteering" },
      { icon: "gift", title: "Donate", text: "With a donation you finance learning materials, rooms and events. The association is recognised as non-profit – we are happy to issue donation receipts.", cta: "See donation account" },
      { icon: "briefcase", title: "Corporate support", text: "Support a specific project, offer internships or become a cooperation partner.", cta: "Discuss cooperation" },
    ],
    stepsTitle: "How to become a member",
    stepsText: "Three simple steps to becoming part of the Miteinander – without bureaucratic hurdles.",
    steps: [
      { title: "Get in touch", text: "Write to us or call the board directly – we are happy to answer all your questions." },
      { title: "Fill in the form", text: "The membership form takes just a few minutes. The annual fee is deliberately kept low." },
      { title: "Welcome to the association", text: "You receive all information about projects, dates and the general assembly – and a warm welcome." },
    ],
    donateTitle: "Donate now",
    donateText:
      "Miteinander in Bergedorf e.V. is recognised as a non-profit organisation. Your donation is tax-deductible in Germany – on request we issue a donation receipt. Every contribution goes directly to our projects in the neighbourhood.",
    donateCta: "Donate now",
    accountHolder: "Account holder",
    fundraisingTitle: "Charity shop & fundraising",
    fundraisingText:
      "Beyond direct donations we fundraise in many ways: flea markets, benefit dinners and stalls at the festival of encounter, as well as through our charity shop. We gladly accept in-kind donations by arrangement. Every euro flows directly into our projects.",
    volunteerTitle: "What volunteers can expect",
    volunteerPoints: [
      "A dedicated contact person and a careful introduction",
      "Flexible hours – even a few hours a month help",
      "Training in intercultural competence and learning support",
      "A warm team and a real insight into the neighbourhood",
    ],
  },
  partners: {
    kicker: "Partners & network",
    title: "Strong partnerships for an open Bergedorf",
    lead: "We work closely with institutions, initiatives and companies that share our values.",
    strategicKicker: "Strategic partner",
    hdTitle: "HolyDigits101",
    hdText:
      "HolyDigits101 is our strategic partner for digitalisation, digital education and communication. Together we develop digital learning formats for young people, modernise the association's processes and make the work of Miteinander in Bergedorf e.V. visible online.",
    hdPoints: [
      "Digital education and media workshops for young people",
      "Website, design and digital communication of the association",
      "Advice on data protection, tools and digital processes",
    ],
    hdCta: "Visit holydigits101.com",
    othersTitle: "Further partners & networks",
    others: [
      { name: "Bezirksamt Bergedorf", text: "Cooperation on district development, integration work and funding programmes." },
      { name: "Fördern und Wohnen (AWO)", text: "Cooperation on social participation, housing advice and support for families." },
      { name: "KulturA", text: "Joint cultural projects and events for the neighbourhood." },
      { name: "LOLA cultural centre", text: "Shared venue for film evenings and cultural formats in Bergedorf." },
      { name: "Charta der Vielfalt", text: "As a signatory we commit to a working and social environment free of prejudice." },
      { name: "Schools in Neuallermöhe", text: "Close cooperation with primary and secondary schools on learning support and parent work." },
    ],
    becomeTitle: "Become a partner",
    becomeText: "Would you like to cooperate with us or fund a project? We look forward to hearing from you.",
  },
  contact: {
    kicker: "Contact & legal notice",
    title: "Talk to us",
    lead: "We welcome questions, ideas and cooperation enquiries – write to us, call us or drop by.",
    formTitle: "Send a message",
    form: { name: "Name", email: "Email", subject: "Subject", message: "Your message", send: "Send message", sent: "Thank you! Your message has been prepared." },
    infoTitle: "Contact details",
    hoursTitle: "Office hours",
    hours: ["Tuesday: 15:00 – 18:00", "Thursday: 15:00 – 18:00", "and by appointment"],
    donateCta: "Donate now",
    imprintTitle: "Legal notice (Impressum)",
    imprintBlocks: [
      { title: "Information according to § 5 TMG", lines: ["Miteinander in Bergedorf e.V.", "Weidenbaumsweg 54", "21035 Hamburg", "Germany", "P.O. Box 808115 · 21015 Hamburg"] },
      { title: "Represented by", lines: ["Henry Akanno (Board)", "Phone: 0174 1349 339"] },
      { title: "Register entry", lines: ["Registered in the register of associations", "Local court of Hamburg", "Register number: VR 22314"] },
      { title: "VAT", lines: ["VAT ID: 17/451/08764"] },
      { title: "Contact", lines: ["Phone: 040 4608 2222", "Email: info@mib-ev.de", "Web: www.mib-ev.de"] },
    ],
    nonProfitTitle: "Non-profit status",
    nonProfitText:
      "Miteinander in Bergedorf e.V. pursues exclusively and directly charitable purposes within the meaning of the German tax code (Abgabenordnung). The association is recognised as a non-profit organisation by the responsible tax office. Donations are tax-deductible; on request we issue a donation receipt (Zuwendungsbescheinigung).",
    legalTitle: "Legal information",
    legal: [
      { title: "Liability for content", text: "The contents of our pages were created with the greatest care. However, we cannot guarantee the accuracy, completeness and timeliness of the content. As a service provider we are responsible for our own content on these pages in accordance with general laws. We are not obliged to monitor transmitted or stored third-party information or to investigate circumstances indicating illegal activity. Obligations to remove or block the use of information under general laws remain unaffected. Liability in this respect is only possible from the time we become aware of a specific legal violation. Upon becoming aware of such violations we will remove the content immediately." },
      { title: "Liability for links", text: "Our offer contains links to external third-party websites over whose content we have no influence. We therefore cannot assume any liability for this external content. The respective provider or operator of the linked pages is always responsible for their content. The linked pages were checked for possible legal violations at the time of linking; illegal content was not recognisable at that time. Permanent content control of the linked pages is not reasonable without concrete evidence of a legal violation. Upon becoming aware of legal violations we will remove such links immediately." },
      { title: "Copyright", text: "The content and works created by the site operators on these pages are subject to German copyright law. Duplication, processing, distribution and any kind of exploitation beyond the limits of copyright require the written consent of the respective author or creator. Downloads and copies of this page are only permitted for private, non-commercial use. Where content on this page was not created by the operator, the copyrights of third parties are respected. If you nevertheless become aware of a copyright infringement, we ask for a corresponding notice. Upon becoming aware of legal violations we will remove such content immediately." },
      { title: "Data protection (privacy policy)", text: "Our website can generally be used without providing personal data. Where personal data (e.g. name, address or email addresses) is collected on our pages, this is always done on a voluntary basis and exclusively to process your enquiry. This data will not be passed on to third parties without your explicit consent. Please note that data transmission over the internet (e.g. by email) may have security gaps; complete protection of data from third-party access is not possible. Use of contact data published under the imprint obligation by third parties for sending unsolicited advertising and information material is hereby expressly objected to." },
      { title: "Data protection and members", text: "The data of our members (name, address, contact details, contribution data) is stored and processed exclusively for association administration within the framework of membership. Data is not passed on to third parties unless this is legally required or necessary to fulfil statutory tasks. Members may request information about their stored data at any time and apply for its correction or deletion. For questions about data protection please contact the board." },
    ],
  },
  footer: {
    about: "Non-profit association for integration, education and intercultural encounter in Hamburg-Bergedorf and Neuallermöhe – founded in 2014.",
    nav: "Navigation",
    contact: "Contact",
    partner: "Strategic partner",
    rights: "All rights reserved.",
    imprint: "Legal notice & privacy",
    madeWith: "Digital implementation in partnership with",
  },
};

export const content = { de, en };
export type Content = typeof de;
